apiVersion: v1
kind: Pod
metadata:
  # pod의 이름은 namespace 내에서 유일해야 함
  name: my-nginx
  namespace: minhyeong
  # labels는 service의 라우팅 대상이 되는 이름. 같은 label이 붙은 여러 pod는 가능하다.
  # service 자원의 selector.app과 일치해야 매핑이 됨.
  labels:
    app: my-nginx
spec:
  containers:
  - name: my-nginx
    image: nginx
    ports:
    - containerPort: 80